# This is a basic workflow to help you get started with Actions

name: Nuitka Build to PythonCI

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    container: highcwu/cheerp-build:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install Nuitka
      - name: Install Nuitka
        run: pip install nuitka
        
      # Nuitka build to WebAssembly test
      - name: Nuitka build to WebAssembly test
        run: cd nuitka_wasm && CC=/opt/cheerp/bin/clang python -m nuitka --module test.py --clang --user-plugin=WebAssemblyPlugin.py
